name: learn-github-actions
on: [push]
jobs:
  Basic_custom_action:
    runs-on: ubuntu-latest
    steps:
      - name: get custom action name
        uses: actions/checkout@v3
      - name: get custom action name
        uses: TamminaRajasekhar/Github_actions@main
      
